# Generated by Django 5.1.2 on 2024-12-03 12:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agent', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom', models.CharField(max_length=20, verbose_name='Nom')),
                ('postnom', models.CharField(max_length=20, verbose_name='Postnom')),
                ('prenom', models.CharField(blank=True, max_length=20, null=True, verbose_name='Prénom')),
                ('sexe', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=10, verbose_name='Sexe')),
                ('lieu_naissance', models.CharField(max_length=50, verbose_name='Lieu de naissance')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('etat_civil', models.CharField(choices=[('Célibataire', 'Célibataire'), ('Marié', 'Marié(e)'), ('Veuf', 'Veuf(ve)'), ('Divorcé', 'Divorcé(e)')], max_length=20, verbose_name='Etat civil')),
                ('type_carte_identite', models.CharField(choices=[('CNI', "Carte Nationale d'Identité"), ('Passeport', 'Passeport'), ('Permis de conduire', 'Permis de conduire'), ('Autre', 'Autre')], max_length=20, verbose_name="Type de carte d'identité")),
                ('num_carte_identite', models.CharField(max_length=50, verbose_name="Numéro de carte d'identité")),
                ('photo_passport', models.ImageField(upload_to='photos_passport/', verbose_name='Photo de passeport')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='photos_profil/', verbose_name='Photo de profil')),
                ('province_residence', models.CharField(max_length=20, verbose_name='Province de résidence')),
                ('ville_residence', models.CharField(max_length=20, verbose_name='Ville de résidence')),
                ('quartier_residence', models.CharField(max_length=20, verbose_name='Quartier de résidence')),
                ('avenue_residence', models.CharField(max_length=20, verbose_name='Avenue de résidence')),
                ('numero_telephone', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide.', regex='^0\\d{9}$')], verbose_name='Numéro de téléphone')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('status', models.BooleanField(default=True)),
                ('reference_code', models.OneToOneField(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrateurs.codesreference', verbose_name='Code de référence')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.CreateModel(
            name='NumerosAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide.', regex='^0\\d{9}$')], verbose_name='Numéro Agent')),
                ('reseau', models.CharField(choices=[('Airtel', 'Airtel'), ('Orange', 'Orange'), ('Vodacom', 'Vodacom'), ('Africel', 'Africel')], max_length=10, verbose_name='Opérateur Réeseau')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agents', verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'Numéro Agent',
                'verbose_name_plural': 'Numéros Agent',
            },
        ),
    ]
