# Generated by Django 5.1.2 on 2024-12-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerosagent',
            name='reseau',
            field=models.CharField(choices=[('Airtel', 'Airtel'), ('Orange', 'Orange'), ('Vodacom', 'Vodacom'), ('Africel', 'Africel'), ('Bank', 'Bank'), ('COOPEC', 'COOPEC')], max_length=10, verbose_name='Opérateur Réeseau'),
        ),
    ]
