# Generated by Django 5.1.2 on 2024-12-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agents',
            name='photo_profil',
        ),
        migrations.AddField(
            model_name='agents',
            name='carte_identite_copy',
            field=models.ImageField(default=None, upload_to='cartes_identite/', verbose_name="Copie de la carte d'identité"),
            preserve_default=False,
        ),
    ]
