# Generated by Django 5.1.2 on 2024-12-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_numerosagent_reseau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerosagent',
            name='numero',
            field=models.CharField(max_length=20, unique=True, verbose_name='Numéro Agent'),
        ),
    ]
