# Generated by Django 5.1.2 on 2025-01-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_alter_numerosagent_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerosagent',
            name='numero',
            field=models.CharField(max_length=150, unique=True, verbose_name='Numéro Agent'),
        ),
        migrations.AlterField(
            model_name='numerosagent',
            name='reseau',
            field=models.CharField(choices=[('Airtel', 'Airtel'), ('Orange', 'Orange'), ('Vodacom', 'Vodacom'), ('Africel', 'Africel'), ('Bank', 'Bank'), ('COOPEC', 'COOPEC'), ('Cash', 'Cash')], max_length=10, verbose_name='Opérateur Réeseau'),
        ),
    ]
