# Generated by Django 5.1.2 on 2024-12-07 14:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membres',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='membre', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom', models.CharField(max_length=20, verbose_name='Nom')),
                ('postnom', models.CharField(max_length=20, verbose_name='Postnom')),
                ('prenom', models.CharField(blank=True, max_length=20, null=True, verbose_name='Prénom')),
                ('sexe', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=10, verbose_name='Sexe')),
                ('lieu_naissance', models.CharField(max_length=50, verbose_name='Lieu de naissance')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('etat_civil', models.CharField(choices=[('Célibataire', 'Célibataire'), ('Marié', 'Marié(e)'), ('Veuf', 'Veuf(ve)'), ('Divorcé', 'Divorcé(e)')], max_length=20, verbose_name='Etat civil')),
                ('type_carte_identite', models.CharField(choices=[('CNI', "Carte Nationale d'Identité"), ('Passeport', 'Passeport'), ('Permis de conduire', 'Permis de conduire'), ('Autre', 'Autre')], max_length=20, verbose_name="Type de carte d'identité")),
                ('num_carte_identite', models.CharField(max_length=50, verbose_name="Numéro de carte d'identité")),
                ('carte_identite_copy', models.ImageField(upload_to='cartes_identite/', verbose_name="Copie de la carte d'identité")),
                ('photo_profile', models.ImageField(upload_to='photo_profile/', verbose_name='Photo de profile')),
                ('numero_residence', models.IntegerField(verbose_name='Numéro de résidence')),
                ('numero_telephone', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Format valide : (+243 ou 0) 996437657', regex='^(\\+243|0)\\d{9}$')], verbose_name='Numéro de téléphone')),
                ('invitation_code', models.CharField(max_length=20, verbose_name="Code d'invitation")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('mois_contribution', models.DateField(auto_now_add=True, verbose_name='Mois de contribution')),
                ('status', models.BooleanField(default=False)),
                ('avenue_residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateurs.avenues', verbose_name='Avenue de résidence')),
                ('commune_residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateurs.communes', verbose_name='Commune de résidence')),
                ('compte_CDF', models.OneToOneField(max_length=15, on_delete=django.db.models.deletion.CASCADE, related_name='membre', to='administrateurs.numeroscompte', verbose_name='Compte CDF')),
                ('compte_USD', models.OneToOneField(max_length=15, on_delete=django.db.models.deletion.CASCADE, to='administrateurs.numeroscompte', verbose_name='Compte USD')),
                ('contribution_mensuelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateurs.contributionsmensuelles', verbose_name='Contribution mensuelle')),
                ('province_residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateurs.provinces', verbose_name='Province de résidence')),
                ('quartier_residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateurs.quartiers', verbose_name='Quartier de résidence')),
                ('reference_code', models.OneToOneField(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrateurs.codesreference', verbose_name='Code de référence')),
                ('ville_residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateurs.villes', verbose_name='Ville de résidence')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
            },
        ),
    ]
