# Generated by Django 5.1.2 on 2024-12-03 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membres',
            name='mois_contribution',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 12, 3, 13, 42, 44, 481660, tzinfo=datetime.timezone.utc), verbose_name='Mois de contribution'),
            preserve_default=False,
        ),
    ]
