# Generated by Django 5.1.2 on 2025-04-15 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateurs', '0002_alter_avenues_nom_alter_communes_nom_and_more'),
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membres',
            name='contribution_mensuelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrateurs.contributionsmensuelles', verbose_name='Contribution mensuelle'),
        ),
        migrations.AlterField(
            model_name='membres',
            name='mois_contribution',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Mois de contribution'),
        ),
    ]
