# Generated by Django 5.1.2 on 2024-12-04 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0002_membres_mois_contribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membres',
            name='photo_profil',
        ),
    ]
