# Generated by Django 4.2 on 2025-07-07 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrateurs', '0005_remove_constantes_type_alter_constantes_key'),
        ('membres', '0003_registre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membres',
            name='avenue_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrateurs.avenues', verbose_name='Avenue de résidence'),
        ),
        migrations.AlterField(
            model_name='membres',
            name='commune_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrateurs.communes', verbose_name='Commune de résidence'),
        ),
        migrations.AlterField(
            model_name='membres',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='membres',
            name='etat_civil',
            field=models.CharField(blank=True, choices=[('Célibataire', 'Célibataire'), ('Marié', 'Marié(e)'), ('Veuf', 'Veuf(ve)'), ('Divorcé', 'Divorcé(e)')], max_length=20, null=True, verbose_name='Etat civil'),
        ),
        migrations.AlterField(
            model_name='membres',
            name='invitation_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Code d'invitation"),
        ),
        migrations.AlterField(
            model_name='membres',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='membres',
            name='num_carte_identite',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Numéro de carte d'identité"),
        ),
        migrations.AlterField(
            model_name='membres',
            name='numero_residence',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numéro de résidence'),
        ),
        migrations.AlterField(
            model_name='membres',
            name='photo_profile',
            field=models.ImageField(blank=True, null=True, upload_to='photo_profile/', verbose_name='Photo de profile'),
        ),
        migrations.AlterField(
            model_name='membres',
            name='province_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrateurs.provinces', verbose_name='Province de résidence'),
        ),
        migrations.AlterField(
            model_name='membres',
            name='quartier_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrateurs.quartiers', verbose_name='Quartier de résidence'),
        ),
        migrations.AlterField(
            model_name='membres',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme')], max_length=10, null=True, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='membres',
            name='type_carte_identite',
            field=models.CharField(blank=True, choices=[('CNI', "Carte Nationale d'Identité"), ('Passeport', 'Passeport'), ('Permis de conduire', 'Permis de conduire'), ('Autre', 'Autre')], max_length=20, null=True, verbose_name="Type de carte d'identité"),
        ),
        migrations.AlterField(
            model_name='membres',
            name='ville_residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrateurs.villes', verbose_name='Ville de résidence'),
        ),
    ]
