# Generated by Django 4.2 on 2025-07-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0004_alter_membres_avenue_residence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membres',
            name='carte_identite_copy',
            field=models.ImageField(upload_to='identite/', verbose_name="Copie de la carte d'identité"),
        ),
        migrations.AlterField(
            model_name='membres',
            name='photo_profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Photo de profile'),
        ),
    ]
