# Generated by Django 4.2 on 2025-07-09 03:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0005_alter_membres_carte_identite_copy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membres',
            name='numero_telephone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Format valide : (243 ou 0) 996437657', regex='^(\\243)\\d{9}$')], verbose_name='Numéro de téléphone'),
        ),
    ]
