# Generated by Django 4.2 on 2025-07-09 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0006_alter_membres_numero_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membres',
            name='numero_telephone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit commencer par '243' et être suivi de 9 chiffres (ex: 243992131675).", regex='^243\\d{9}$')], verbose_name='Numéro de téléphone'),
        ),
    ]
