# Generated by Django 5.1.2 on 2024-12-04 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrateurs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrateurs',
            name='photo_profil',
        ),
    ]
