# Generated by Django 5.1.2 on 2024-12-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avenues',
            name='nom',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='communes',
            name='nom',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='quartiers',
            name='nom',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='villes',
            name='nom',
            field=models.CharField(max_length=45),
        ),
    ]
