# Generated by Django 5.1.2 on 2025-04-15 09:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateurs', '0002_alter_avenues_nom_alter_communes_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='numeroscompte',
            name='solde',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='solde'),
        ),
    ]
