# Generated by Django 5.1.2 on 2025-04-22 10:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateurs', '0003_numeroscompte_solde'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('type', models.CharField(choices=[('PERCENTAGE', 'Pourcentage'), ('CURRENCY', 'Monétaire'), ('FLOAT', 'Nombre décimal'), ('EXCHANGE_RATE', 'Taux de change')], default='FLOAT', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrateurs.administrateurs')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueConstantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.DecimalField(decimal_places=5, max_digits=10)),
                ('new_value', models.DecimalField(decimal_places=5, max_digits=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrateurs.administrateurs')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='administrateurs.constantes')),
            ],
        ),
    ]
