# Generated by Django 5.1.2 on 2025-04-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateurs', '0004_constantes_historiqueconstantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constantes',
            name='type',
        ),
        migrations.AlterField(
            model_name='constantes',
            name='key',
            field=models.CharField(choices=[('abonnement_annuel', 'Abonnement annuel (1ère année)'), ('recharge_momo', 'Recharge via Mobile Money'), ('retrait_momo', 'Retrait via Mobile Money'), ('recharge_agent', 'Recharge via Agent'), ('retrait_agent', 'Retrait via Agent'), ('recharge_invest', 'Recharge Investissement'), ('retrait_invest', 'Retrait Investissement'), ('recharge_objectif', 'Recharge Objectif'), ('retrait_objectif', 'Retrait Objectif'), ('paiement_service', 'Paiement Service'), ('transfert_pp', 'Transfert PP'), ('retrait_benefice', 'Retrait bénéfices'), ('taux_change', 'Taux de change')], max_length=100, unique=True),
        ),
    ]
