# Generated by Django 5.1.2 on 2024-11-21 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membres', '0001_initial'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesObjectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom du type d'objectif")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Objectifs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('membre', 'membre'), ('organisation', 'organisation')], max_length=20, verbose_name='Opérateur')),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'objectif")),
                ('description', models.TextField(verbose_name='Description')),
                ('montant_USD', models.FloatField(blank=True, null=True, verbose_name='Montant en USD')),
                ('montant_CDF', models.FloatField(blank=True, null=True, verbose_name='Montant en CDF')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('status', models.CharField(choices=[('En cours', 'En cours'), ('Atteint', 'Atteint')], default='En cours', max_length=20, verbose_name='Statut')),
                ('membre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membres.membres', verbose_name='Client')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.organisations', verbose_name='Organisations')),
                ('type_objectif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objectifs.typesobjectif', verbose_name="Type d'objectif")),
            ],
        ),
    ]
