# Generated by Django 5.1.2 on 2024-11-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectifs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectifs',
            old_name='type_objectif',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='objectifs',
            name='montant_CDF',
        ),
        migrations.RemoveField(
            model_name='objectifs',
            name='montant_USD',
        ),
        migrations.AddField(
            model_name='objectifs',
            name='devise',
            field=models.CharField(choices=[('CDF', 'CDF'), ('USD', 'USD')], default=0, max_length=10, verbose_name='Devise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectifs',
            name='montant',
            field=models.FloatField(default=0, verbose_name='Montant'),
        ),
        migrations.AddField(
            model_name='objectifs',
            name='montant_cible',
            field=models.FloatField(default=0, verbose_name='Montant cible'),
            preserve_default=False,
        ),
    ]
