# Generated by Django 5.1.2 on 2025-06-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectifs', '0002_alter_objectifs_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectifs',
            name='statut',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Atteint', 'Atteint'), ('Retiré', 'Retiré'), ('Epuisé', 'Epuisé'), ('Archivé', 'Archivé')], default='En cours', max_length=20, verbose_name='Statut'),
        ),
    ]
