# Generated by Django 5.1.2 on 2024-11-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectifs', '0002_rename_type_objectif_objectifs_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectifs',
            name='status',
        ),
        migrations.AddField(
            model_name='objectifs',
            name='statut',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Atteint', 'Atteint'), ('Epuisé', 'Epuisé'), ('Annulé', 'Annulé')], default='En cours', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='objectifs',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
