# Generated by Django 5.1.2 on 2024-12-12 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrateurs', '0001_initial'),
        ('agents', '0001_initial'),
        ('membres', '0001_initial'),
        ('objectifs', '0001_initial'),
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesPret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45, verbose_name='Nom du type de pret')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('taux_interet', models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Taux d'intérêt (%)")),
                ('delai_remboursement', models.IntegerField(verbose_name='Delai de remboursement')),
            ],
            options={
                'verbose_name': 'Type de pret',
                'verbose_name_plural': 'Types de prets',
            },
        ),
        migrations.CreateModel(
            name='Prets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant du pret')),
                ('montant_remboursé', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant remboursé')),
                ('solde_remboursé', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Solde remboursé')),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], max_length=3, verbose_name='Devise')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('date_approbation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('date_remboursement', models.DateTimeField(verbose_name='Date de remboursement')),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Remboursé', 'Remboursé'), ('Annulé', 'Annulé')], default='En attente', max_length=20, verbose_name='Statut')),
                ('administrateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrateurs.administrateurs', verbose_name='Administrateur')),
                ('membre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membres.membres', verbose_name='Membres')),
            ],
            options={
                'verbose_name': 'Prêt',
                'verbose_name_plural': 'Prêts',
            },
        ),
        migrations.CreateModel(
            name='Benefices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant du bénéfice')),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], max_length=3, verbose_name='Devise')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date du bénéfice')),
                ('statut', models.BooleanField(default=True, verbose_name='Statut')),
                ('membre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membres.membres', verbose_name='Membre')),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.prets', verbose_name='Prêt')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('membre', 'membre'), ('organisation', 'organisation')], default='membre', max_length=20, verbose_name='Opérateur')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], max_length=3, verbose_name='Devise')),
                ('preuve', models.ImageField(blank=True, upload_to='preuves/transactions/', verbose_name='Preuve de transaction')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('date_approbation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('retrait', 'Retrait'), ('retrait_tout', 'Retrait tout'), ('retrait_objectif', 'Retrait objectif'), ('annulation_objectif', 'Annulation objectif'), ('transfert', 'Transfert'), ('depot_objectif', 'Dépôt objectif'), ('depot_inscription', 'Dépôt inscription'), ('contribution', 'Contribution'), ('pret', 'Prêt'), ('remboursement_pret', 'Remboursement pret')], max_length=20, verbose_name='Type de transaction')),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté'), ('Remboursé', 'Remboursé'), ('Annulé', 'Annulé')], default='Demande', max_length=20, verbose_name='Statut')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrateurs.administrateurs', verbose_name='Administrateurs')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.agents', verbose_name='Agents')),
                ('membre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membres.membres', verbose_name='Membres')),
                ('numero_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.numerosagent', verbose_name="Numéro de l'agent")),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.organisations', verbose_name='Organisations')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='RetraitsObjectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(verbose_name='Montant')),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], max_length=3, verbose_name='Devise')),
                ('frais', models.FloatField(verbose_name='Frais')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('date_approbation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté'), ('Annulé', 'Annulé')], default='En attente', max_length=20, verbose_name='Statut')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membres.membres', verbose_name='Membres')),
                ('objectif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectifs.objectifs', verbose_name='Objectifs')),
                ('transaction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='retrait_objectif', to='transactions.transactions', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Retrait objectif',
                'verbose_name_plural': 'Retraits objectifs',
            },
        ),
        migrations.CreateModel(
            name='Retraits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(verbose_name='Montant')),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], max_length=3, verbose_name='Devise')),
                ('frais', models.FloatField(verbose_name='Frais')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('date_approbation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté'), ('Annulé', 'Annulé')], default='En attente', max_length=20, verbose_name='Statut')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membres.membres', verbose_name='Membres')),
                ('transaction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='retrait', to='transactions.transactions', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Retraits',
                'verbose_name_plural': 'Retraits',
            },
        ),
        migrations.CreateModel(
            name='RemboursementsPret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant du remboursement')),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], max_length=3, verbose_name='Devise')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de remboursement')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté'), ('Annulé', 'Annulé')], default='En attente', max_length=20, verbose_name='Statut')),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.prets', verbose_name='Pret')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remboursement_pret', to='transactions.transactions', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Remboursement de pret',
                'verbose_name_plural': 'Remboursements de prets',
            },
        ),
        migrations.AddField(
            model_name='prets',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pret', to='transactions.transactions', verbose_name='Transaction'),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type_notification', models.CharField(choices=[('retrait', 'Retrait'), ('retrait_tout', 'Retrait tout'), ('retrait_objectif', 'Retrait objectif'), ('annulation_objectif', 'Annulation objectif'), ('transfert', 'Transfert'), ('depot_objectif', 'Dépôt objectif'), ('depot_inscription', 'Dépôt inscription'), ('contribution', 'Contribution'), ('pret', 'Prêt'), ('remboursement_pret', 'Remboursement pret'), (None, None)], default=None, max_length=50, verbose_name='Type de notification')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('lu', models.BooleanField(default=False, verbose_name='Confirmation de lecture')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='transactions.transactions', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='Fidelites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(verbose_name='Point de fidélité')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membres.membres', verbose_name='membre')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transactions', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Fidélité',
                'verbose_name_plural': 'Fidélités',
            },
        ),
        migrations.CreateModel(
            name='DepotsObjectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(verbose_name='Montant')),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], max_length=3, verbose_name='Devise')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('date_approbation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté'), ('Annulé', 'Annulé')], default='En attente', max_length=20, verbose_name='Statut')),
                ('objectif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectifs.objectifs', verbose_name='Objectifs')),
                ('transaction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='depot_objectif', to='transactions.transactions', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Dépôt objectif',
                'verbose_name_plural': 'Dépôts objectifs',
            },
        ),
        migrations.CreateModel(
            name='DepotsInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(default=10, verbose_name='Montant')),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], default='USD', max_length=3, verbose_name='Devise')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('date_approbation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté'), ('Annulé', 'Annulé')], default='En attente', max_length=20, verbose_name='Statut')),
                ('membre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membres.membres', verbose_name='Membres')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depot_inscription', to='transactions.transactions', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Dépôt inscription',
                'verbose_name_plural': 'Dépôts inscriptions',
            },
        ),
        migrations.CreateModel(
            name='Contributions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(verbose_name='Montant')),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], max_length=3, verbose_name='Devise')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('date_approbation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('mois', models.DateField(verbose_name='Mois')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté'), ('Annulé', 'Annulé')], default='En attente', max_length=20, verbose_name='Statut')),
                ('transaction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contribution', to='transactions.transactions', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
            },
        ),
        migrations.CreateModel(
            name='AnnulationObjectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(verbose_name='Montant')),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], max_length=3, verbose_name='Devise')),
                ('frais', models.FloatField(verbose_name='Frais')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('date_approbation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté'), ('Annulé', 'Annulé')], default='En attente', max_length=20, verbose_name='Statut')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membres.membres', verbose_name='Membres')),
                ('objectif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectifs.objectifs', verbose_name='Objectifs')),
                ('transaction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='annulation_objectif', to='transactions.transactions', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Annulation objectif',
                'verbose_name_plural': 'Annulations objectifs',
            },
        ),
        migrations.CreateModel(
            name='Transferts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(verbose_name='Montant')),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], max_length=3, verbose_name='Devise')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('date_approbation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('expediteur', models.CharField(choices=[('membre', 'membre'), ('organisation', 'organisation')], max_length=20, verbose_name='Opérateur')),
                ('destinataire', models.CharField(choices=[('membre', 'membre'), ('organisation', 'organisation')], max_length=20, verbose_name='Opérateur')),
                ('motif', models.TextField(verbose_name='Motif')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('membre_destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membres_destinataires', to='membres.membres', verbose_name='Membres')),
                ('membre_expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membres_expediteurs', to='membres.membres', verbose_name='Membres')),
                ('organisation_destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisations_destinataires', to='organisations.organisations', verbose_name='Organisation')),
                ('organisation_expeditrice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisations_expeditrices', to='organisations.organisations', verbose_name='Organisation')),
                ('transaction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfert', to='transactions.transactions', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Transferts',
                'verbose_name_plural': 'Transferts',
            },
        ),
        migrations.AddField(
            model_name='prets',
            name='type_pret',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.typespret', verbose_name='Type de pret'),
        ),
    ]
