# Generated by Django 5.1.2 on 2024-12-24 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant du bénéfice')),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], max_length=3, verbose_name='Devise')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('type', models.CharField(choices=[('depot_inscription', 'Dépôt inscription'), ('retrait', 'Retrait'), ('retrait_tout', 'Retrait tout'), ('annulation_objectif', 'Annulation objectif'), ('remboursement_pret', 'Remboursement pret')], max_length=20, verbose_name='Type de balance')),
                ('statut', models.BooleanField(default=True, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Balance Admin',
                'verbose_name_plural': 'Balance Admin',
            },
        ),
        migrations.AlterField(
            model_name='notifications',
            name='type_notification',
            field=models.CharField(choices=[('retrait', 'Retrait'), ('retrait_tout', 'Retrait tout'), ('retrait_admin', 'Retrait admin'), ('retrait_objectif', 'Retrait objectif'), ('annulation_objectif', 'Annulation objectif'), ('transfert', 'Transfert'), ('depot_objectif', 'Dépôt objectif'), ('depot_inscription', 'Dépôt inscription'), ('contribution', 'Contribution'), ('pret', 'Prêt'), ('remboursement_pret', 'Remboursement pret'), (None, None)], default=None, max_length=50, verbose_name='Type de notification'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('retrait', 'Retrait'), ('retrait_tout', 'Retrait tout'), ('retrait_admin', 'Retrait admin'), ('retrait_objectif', 'Retrait objectif'), ('annulation_objectif', 'Annulation objectif'), ('transfert', 'Transfert'), ('depot_objectif', 'Dépôt objectif'), ('depot_inscription', 'Dépôt inscription'), ('contribution', 'Contribution'), ('pret', 'Prêt'), ('remboursement_pret', 'Remboursement pret')], max_length=20, verbose_name='Type de transaction'),
        ),
        migrations.CreateModel(
            name='RetraitsAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(verbose_name='Montant')),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], max_length=3, verbose_name='Devise')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('date_approbation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté'), ('Annulé', 'Annulé')], default='En attente', max_length=20, verbose_name='Statut')),
                ('transaction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='retrait_admin', to='transactions.transactions', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Retraits Admin',
                'verbose_name_plural': 'Retraits Admin',
            },
        ),
    ]
