# Generated by Django 5.1.2 on 2024-11-21 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depotsinscription',
            name='transaction',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='depot_inscription', to='transactions.transactions', verbose_name='Transaction'),
        ),
        migrations.AlterField(
            model_name='depotsobjectif',
            name='transaction',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='depot_objectif', to='transactions.transactions', verbose_name='Transaction'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='operateur',
            field=models.CharField(choices=[('membre', 'membre'), ('organisation', 'organisation')], default='membre', max_length=20, verbose_name='Opérateur'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='statut',
            field=models.CharField(choices=[('Initialisation', 'Initialisation'), ('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté')], default='Initialisation', max_length=20, verbose_name='Statut'),
        ),
    ]
