# Generated by Django 5.1.2 on 2024-12-03 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributions',
            name='mois',
            field=models.DateField(default=datetime.datetime(2024, 12, 3, 13, 42, 56, 536903, tzinfo=datetime.timezone.utc), verbose_name='Mois'),
            preserve_default=False,
        ),
    ]
