# Generated by Django 5.1.2 on 2024-12-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_balanceadmin_alter_notifications_type_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceadmin',
            name='type',
            field=models.CharField(choices=[('pret', 'Pret'), ('depot_inscription', 'Dépôt inscription'), ('retrait', 'Retrait'), ('retrait_tout', 'Retrait tout'), ('annulation_objectif', 'Annulation objectif'), ('remboursement_pret', 'Remboursement pret')], max_length=20, verbose_name='Type de balance'),
        ),
        migrations.AlterField(
            model_name='prets',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Remboursé', 'Remboursé'), ('Depassé', 'Depassé'), ('Annulé', 'Annulé')], default='En attente', max_length=20, verbose_name='Statut'),
        ),
    ]
