# Generated by Django 5.1.2 on 2024-11-28 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_depotsinscription_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributions',
            name='operateur',
        ),
    ]
