# Generated by Django 5.1.2 on 2024-12-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_balanceadmin_type_alter_prets_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='depotsinscription',
            name='preuve',
            field=models.ImageField(blank=True, upload_to='preuves/depots_inscriptions/', verbose_name='Preuve de depot'),
        ),
    ]
