# Generated by Django 5.1.2 on 2024-11-29 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateurs', '0001_initial'),
        ('transactions', '0003_remove_contributions_operateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prêts',
            name='administrateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrateurs.administrateurs', verbose_name='Administrateur'),
        ),
    ]
