# Generated by Django 5.1.2 on 2024-11-30 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0001_initial'),
        ('transactions', '0004_alter_prêts_administrateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prêts',
            name='transaction',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='prêt', to='transactions.transactions', verbose_name='Transaction'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='statut',
            field=models.CharField(choices=[('Initialisation', 'Initialisation'), ('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté'), ('Remboursé', 'Remboursé'), ('Annulé', 'Annulé')], default='Initialisation', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='Benefices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant du bénéfice')),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], max_length=3, verbose_name='Devise')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date du bénéfice')),
                ('statut', models.BooleanField(default=True, verbose_name='Statut')),
                ('membre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membres.membres', verbose_name='Membre')),
                ('prêt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.prêts', verbose_name='Prêt')),
            ],
        ),
    ]
