# Generated by Django 5.1.2 on 2025-01-04 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0001_initial'),
        ('objectifs', '0002_alter_objectifs_nom'),
        ('transactions', '0004_depotsinscription_preuve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annulationobjectif',
            name='membre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membres.membres', verbose_name='Membres'),
        ),
        migrations.AlterField(
            model_name='annulationobjectif',
            name='objectif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objectifs.objectifs', verbose_name='Objectifs'),
        ),
        migrations.AlterField(
            model_name='depotsobjectif',
            name='objectif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objectifs.objectifs', verbose_name='Objectifs'),
        ),
        migrations.AlterField(
            model_name='retraitsobjectif',
            name='membre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membres.membres', verbose_name='Membres'),
        ),
        migrations.AlterField(
            model_name='retraitsobjectif',
            name='objectif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objectifs.objectifs', verbose_name='Objectifs'),
        ),
    ]
