# Generated by Django 5.1.2 on 2024-12-02 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_prêts_transaction_alter_transactions_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prêts',
            name='type_prêt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.typesprêt', verbose_name='Type de prêt'),
        ),
    ]
