# Generated by Django 5.1.2 on 2025-04-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_annulationobjectif_membre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributions',
            name='mois',
            field=models.DateField(blank=True, null=True, verbose_name='Mois'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='preuve',
            field=models.ImageField(blank=True, null=True, upload_to='preuves/transactions/', verbose_name='Preuve de transaction'),
        ),
    ]
