# Generated by Django 5.1.2 on 2025-04-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_contributions_mois_alter_transactions_preuve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annulationobjectif',
            name='frais',
            field=models.FloatField(blank=True, null=True, verbose_name='Frais'),
        ),
    ]
