# Generated by Django 5.1.2 on 2025-04-25 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_annulationobjectif_frais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='type_notification',
            field=models.CharField(choices=[('retrait', 'Retrait'), ('retrait_tout', 'Retrait tout'), ('retrait_admin', 'Retrait admin'), ('retrait_objectif', 'Retrait objectif'), ('annulation_objectif', 'Annulation objectif'), ('transfert', 'Transfert'), ('depot_objectif', 'Dépôt objectif'), ('depot_inscription', 'Dépôt inscription'), ('contribution', 'Contribution'), ('pret', 'Prêt'), ('remboursement_pret', 'Remboursement pret'), ('recharger_compte', 'Recharger compte'), (None, None)], default=None, max_length=50, verbose_name='Type de notification'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('retrait', 'Retrait'), ('retrait_tout', 'Retrait tout'), ('retrait_admin', 'Retrait admin'), ('retrait_objectif', 'Retrait objectif'), ('annulation_objectif', 'Annulation objectif'), ('transfert', 'Transfert'), ('depot_objectif', 'Dépôt objectif'), ('depot_inscription', 'Dépôt inscription'), ('contribution', 'Contribution'), ('pret', 'Prêt'), ('remboursement_pret', 'Remboursement pret'), ('recharger_compte', 'Recharger compte')], max_length=20, verbose_name='Type de transaction'),
        ),
        migrations.CreateModel(
            name='Solde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=4, max_digits=10)),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], max_length=3, verbose_name='Devise')),
                ('account_sender', models.CharField(max_length=15, verbose_name="Numéro de téléphone de l'expéditeur")),
                ('frais_retrait', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transactions')),
            ],
        ),
    ]
