# Generated by Django 5.1.2 on 2025-04-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_notifications_type_notification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solde',
            options={'verbose_name': 'Solde', 'verbose_name_plural': 'soldes'},
        ),
    ]
