# Generated by Django 5.1.2 on 2025-04-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_solde_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='prets',
            name='mode_payement',
            field=models.CharField(choices=[('hebdomadaire', 'Hebdomadaire'), ('mensuel', 'Mensuel'), ('annuel', 'annuel')], default='hebdomadaire', max_length=15, verbose_name='mode payement'),
        ),
        migrations.AddField(
            model_name='prets',
            name='montant_payer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='montant a payer'),
        ),
        migrations.AddField(
            model_name='typespret',
            name='delais_traitement',
            field=models.IntegerField(default=24, verbose_name='Délai de traitement (heures)'),
        ),
    ]
