# Generated by Django 5.1.2 on 2025-05-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_prets_mode_payement_prets_montant_payer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typespret',
            name='delai_remboursement',
            field=models.IntegerField(verbose_name='Delai de remboursement(en mois)'),
        ),
    ]
