# Generated by Django 5.1.2 on 2025-05-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_alter_typespret_delai_remboursement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typespret',
            name='nom',
            field=models.CharField(max_length=45, unique=True, verbose_name='Nom du type de pret'),
        ),
    ]
