# Generated by Django 5.1.2 on 2025-05-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_typespret_nom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solde',
            options={'verbose_name': 'Solde', 'verbose_name_plural': 'Soldes'},
        ),
    ]
