# Generated by Django 5.1.2 on 2025-05-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_solde_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='typespret',
            name='montant_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant maximum'),
        ),
        migrations.AddField(
            model_name='typespret',
            name='montant_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant minimum'),
        ),
    ]
