# Generated by Django 5.1.2 on 2025-05-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_typespret_montant_max_typespret_montant_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='typespret',
            name='investissement_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Investissement minimum'),
        ),
    ]
