# Generated by Django 5.1.2 on 2025-05-14 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0002_alter_membres_contribution_mensuelle_and_more'),
        ('transactions', '0015_typespret_investissement_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceadmin',
            name='type',
            field=models.CharField(choices=[('pret', 'Pret'), ('depot_inscription', 'Dépôt inscription'), ('retrait', 'Retrait'), ('retrait_investissement', 'Retrait investissement'), ('annulation_objectif', 'Annulation objectif'), ('remboursement_pret', 'Remboursement pret')], max_length=30, verbose_name='Type de balance'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='type_notification',
            field=models.CharField(choices=[('retrait', 'Retrait'), ('retrait_tout', 'Retrait tout'), ('retrait_admin', 'Retrait admin'), ('retrait_objectif', 'Retrait objectif'), ('annulation_objectif', 'Annulation objectif'), ('transfert', 'Transfert'), ('depot_objectif', 'Dépôt objectif'), ('depot_inscription', 'Dépôt inscription'), ('contribution', 'Contribution'), ('pret', 'Prêt'), ('remboursement_pret', 'Remboursement pret'), ('recharger_compte', 'Recharger compte'), ('retrait_investissement', 'retrait investissement'), (None, None)], default=None, max_length=50, verbose_name='Type de notification'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('retrait', 'Retrait'), ('retrait_tout', 'Retrait tout'), ('retrait_admin', 'Retrait admin'), ('retrait_objectif', 'Retrait objectif'), ('annulation_objectif', 'Annulation objectif'), ('transfert', 'Transfert'), ('depot_objectif', 'Dépôt objectif'), ('depot_inscription', 'Dépôt inscription'), ('contribution', 'Contribution'), ('pret', 'Prêt'), ('remboursement_pret', 'Remboursement pret'), ('recharger_compte', 'Recharger compte'), ('retrait_investissement', 'retrait investissement')], max_length=30, verbose_name='Type de transaction'),
        ),
        migrations.CreateModel(
            name='RetraitContributions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(verbose_name='Montant')),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], max_length=3, verbose_name='Devise')),
                ('frais', models.FloatField(verbose_name='Frais')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('date_approbation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté'), ('Annulé', 'Annulé')], default='En attente', max_length=20, verbose_name='Statut')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membres.membres', verbose_name='Membres')),
                ('transaction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='retrait_investissement', to='transactions.transactions', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Retraits',
                'verbose_name_plural': 'Retraits',
            },
        ),
    ]
