# Generated by Django 5.1.2 on 2025-05-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_alter_balanceadmin_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retraits',
            name='montant_recu',
            field=models.FloatField(blank=True, null=True, verbose_name='Montant recus'),
        ),
    ]
