# Generated by Django 5.1.2 on 2025-05-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_retraits_montant_recu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retraitsobjectif',
            name='frais',
            field=models.FloatField(blank=True, null=True, verbose_name='Frais'),
        ),
    ]
