# Generated by Django 5.1.2 on 2025-05-27 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_alter_retraitsobjectif_frais'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcheancePret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('date_echeance', models.DateTimeField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payé', 'Payé'), ('échoué', 'Échoué'), ('reporté', 'Reporté')], default='en_attente', max_length=20)),
                ('penalite', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('grace_jusqua', models.DateTimeField(blank=True, null=True)),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='transactions.prets')),
            ],
        ),
    ]
