# Generated by Django 5.1.2 on 2025-05-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_echeancepret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceadmin',
            name='montant',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Montant du bénéfice'),
        ),
        migrations.AlterField(
            model_name='benefices',
            name='montant',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Montant du bénéfice'),
        ),
        migrations.AlterField(
            model_name='echeancepret',
            name='montant',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='echeancepret',
            name='penalite',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='prets',
            name='montant',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Montant du pret'),
        ),
        migrations.AlterField(
            model_name='prets',
            name='montant_payer',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10, verbose_name='montant a payer'),
        ),
        migrations.AlterField(
            model_name='prets',
            name='montant_remboursé',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Montant remboursé'),
        ),
        migrations.AlterField(
            model_name='prets',
            name='solde_remboursé',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='Solde remboursé'),
        ),
        migrations.AlterField(
            model_name='remboursementspret',
            name='montant',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Montant du remboursement'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='montant',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='typespret',
            name='investissement_min',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Investissement minimum'),
        ),
        migrations.AlterField(
            model_name='typespret',
            name='montant_max',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Montant maximum'),
        ),
        migrations.AlterField(
            model_name='typespret',
            name='montant_min',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Montant minimum'),
        ),
        migrations.AlterField(
            model_name='typespret',
            name='taux_interet',
            field=models.DecimalField(decimal_places=5, max_digits=5, verbose_name="Taux d'intérêt (%)"),
        ),
    ]
