# Generated by Django 5.1.2 on 2025-05-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_alter_balanceadmin_montant_alter_benefices_montant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typespret',
            name='taux_interet',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name="Taux d'intérêt (%)"),
        ),
    ]
