# Generated by Django 5.1.2 on 2025-06-03 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_alter_typespret_taux_interet'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefices',
            name='remboursement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.remboursementspret', verbose_name='Remboursement associé'),
        ),
    ]
