# Generated by Django 5.1.2 on 2025-06-12 10:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_benefices_remboursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeancepret',
            name='montant_du',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00'), help_text='Montant restant à payer pour cette échéance.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='echeancepret',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('payé', 'Payé'), ('échoué', 'Échoué'), ('reporté', 'Reporté'), ('partiellement_payé', 'Partiellement payé'), ('en_retard', 'En retard')], default='en_attente', max_length=20),
        ),
    ]
