# Generated by Django 4.2 on 2025-06-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_echeancepret_montant_du_alter_echeancepret_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='type_notification',
            field=models.CharField(choices=[('retrait_benefice', 'Retrait Benefice'), ('retrait_tout', 'Retrait tout'), ('retrait_admin', 'Retrait admin'), ('retrait_objectif', 'Retrait objectif'), ('annulation_objectif', 'Annulation objectif'), ('transfert', 'Transfert'), ('depot_objectif', 'Dépôt objectif'), ('depot_inscription', 'Dépôt inscription'), ('contribution', 'Contribution'), ('pret', 'Prêt'), ('remboursement_pret', 'Remboursement pret'), ('recharger_compte', 'Recharger compte'), ('retrait_investissement', 'retrait investissement'), (None, None)], default=None, max_length=50, verbose_name='Type de notification'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('retrait_benefice', 'Retrait Benefice'), ('retrait_tout', 'Retrait tout'), ('retrait_admin', 'Retrait admin'), ('retrait_objectif', 'Retrait objectif'), ('annulation_objectif', 'Annulation objectif'), ('transfert', 'Transfert'), ('depot_objectif', 'Dépôt objectif'), ('depot_inscription', 'Dépôt inscription'), ('contribution', 'Contribution'), ('pret', 'Prêt'), ('remboursement_pret', 'Remboursement pret'), ('recharger_compte', 'Recharger compte'), ('retrait_investissement', 'retrait investissement')], max_length=30, verbose_name='Type de transaction'),
        ),
        migrations.DeleteModel(
            name='RetraitContributions',
        ),
    ]
