# Generated by Django 4.2 on 2025-06-23 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_alter_notifications_type_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceadmin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 23, 12, 9, 35, 892953, tzinfo=datetime.timezone.utc), verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='balanceadmin',
            name='montant',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Montant du bénéfice'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='montant',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Montant'),
        ),
    ]
