# Generated by Django 4.2 on 2025-06-23 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_alter_balanceadmin_date_alter_balanceadmin_montant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceadmin',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
    ]
