# Generated by Django 4.2 on 2025-06-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0026_alter_balanceadmin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceadmin',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
