# Generated by Django 4.2 on 2025-06-23 12:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0027_alter_balanceadmin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annulationobjectif',
            name='frais',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Frais'),
        ),
        migrations.AlterField(
            model_name='annulationobjectif',
            name='montant',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='benefices',
            name='montant',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Montant du bénéfice'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='montant',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='depotsinscription',
            name='montant',
            field=models.DecimalField(decimal_places=4, default=10, max_digits=15, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='depotsobjectif',
            name='montant',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='echeancepret',
            name='montant',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='echeancepret',
            name='montant_du',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Montant restant à payer pour cette échéance.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='echeancepret',
            name='penalite',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='prets',
            name='montant',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Montant du pret'),
        ),
        migrations.AlterField(
            model_name='prets',
            name='montant_payer',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15, verbose_name='montant a payer'),
        ),
        migrations.AlterField(
            model_name='prets',
            name='montant_remboursé',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Montant remboursé'),
        ),
        migrations.AlterField(
            model_name='prets',
            name='solde_remboursé',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Solde remboursé'),
        ),
        migrations.AlterField(
            model_name='remboursementspret',
            name='montant',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Montant du remboursement'),
        ),
        migrations.AlterField(
            model_name='retraits',
            name='frais',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Frais'),
        ),
        migrations.AlterField(
            model_name='retraits',
            name='montant',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='retraits',
            name='montant_recu',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Montant recus'),
        ),
        migrations.AlterField(
            model_name='retraitsadmin',
            name='montant',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='retraitsobjectif',
            name='frais',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Frais'),
        ),
        migrations.AlterField(
            model_name='retraitsobjectif',
            name='montant',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='solde',
            name='frais_retrait',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='solde',
            name='montant',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transferts',
            name='montant',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='typespret',
            name='investissement_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Investissement minimum'),
        ),
        migrations.AlterField(
            model_name='typespret',
            name='montant_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Montant maximum'),
        ),
        migrations.AlterField(
            model_name='typespret',
            name='montant_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Montant minimum'),
        ),
        migrations.AlterField(
            model_name='typespret',
            name='taux_interet',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name="Taux d'intérêt (%)"),
        ),
    ]
