# Generated by Django 4.2 on 2025-07-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0028_alter_annulationobjectif_frais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone du client'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='serdipay_raw_response',
            field=models.JSONField(blank=True, null=True, verbose_name='Réponse brute SerdiPay'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='serdipay_session_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Session SerdiPay'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='serdipay_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Transaction SerdiPay'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté'), ('Remboursé', 'Remboursé'), ('Annulé', 'Annulé'), ('Échoué', 'Échoué')], default='En attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddIndex(
            model_name='transactions',
            index=models.Index(fields=['serdipay_session_id'], name='transaction_serdipa_dd7b13_idx'),
        ),
        migrations.AddIndex(
            model_name='transactions',
            index=models.Index(fields=['serdipay_transaction_id'], name='transaction_serdipa_31ca11_idx'),
        ),
        migrations.AddIndex(
            model_name='transactions',
            index=models.Index(fields=['client_phone'], name='transaction_client__e38adf_idx'),
        ),
    ]
