# Generated by Django 4.2 on 2025-07-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0029_transactions_client_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solde',
            name='account_sender',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Numéro de téléphone de l'expéditeur"),
        ),
    ]
