# Generated by Django 4.2 on 2025-07-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0030_alter_solde_account_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depotsinscription',
            name='montant',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Montant'),
        ),
    ]
