# Generated by Django 5.1.2 on 2024-12-05 03:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisations',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='organisation', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('id_national', models.CharField(max_length=255, verbose_name='Identifiant national')),
                ('rccm', models.CharField(max_length=255, verbose_name='RCCM')),
                ('impot', models.CharField(max_length=255, verbose_name='Impot')),
                ('id_national_copy', models.CharField(max_length=255, verbose_name="Copie de l'identifiant national")),
                ('numero_telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Numéro de téléphone')),
                ('reference_code', models.CharField(blank=True, max_length=45, null=True, verbose_name='Code de référence')),
                ('invitation_code', models.CharField(blank=True, max_length=255, null=True, verbose_name="Code d'invitation")),
                ('access_code', models.CharField(blank=True, max_length=255, null=True, verbose_name="Code d'accès")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('compte_CDF', models.FloatField(default=0, verbose_name='Compte en CDF')),
                ('compte_USD', models.FloatField(default=0, verbose_name='Compte en USD')),
                ('status', models.BooleanField(default=False)),
                ('avenue_residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateurs.avenues', verbose_name='Avenue de résidence')),
                ('province_residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateurs.provinces', verbose_name='Province de résidence')),
                ('quartier_residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateurs.quartiers', verbose_name='Quartier de résidence')),
                ('ville_residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateurs.villes', verbose_name='Ville de résidence')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
            },
        ),
    ]
