"""
Django settings for muhangiki_wallet project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import pymysql
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-0n!^rc92pcf=frp0#n&gp8+pqcso4crpd8!cs7_j3y=dh+4l^x')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["https://muhangikiwallet.com","muhangikiwallet.com", "*"]

# Encodage UTF-8
DEFAULT_CHARSET = 'utf-8'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'whitenoise.runserver_nostatic',
    'crispy_forms',
    'django_bootstrap5',
    'agents',
    'membres',
    "objectifs",
    'transactions',
    'organisations',
    'administrateurs',
    'muhangiki_wallet',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CSRF_TRUSTED_ORIGINS = ["https://muhangikiwallet.com"]


ROOT_URLCONF = 'muhangiki_wallet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'muhangiki_wallet' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'muhangiki_wallet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'defaul': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'muhangikiwallet_muhangikiwallet', # Remplacez par le nom de votre base de données
        'USER': 'muhangikiwallet_muhangik', # Remplacez par votre utilisateur de base de données
        'PASSWORD': '@!rm0n123#', # Remplacez par votre mot de passe de base de données
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS':{
            'init_command':"SET sql_mode='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION'"
            },
        
    },
    'mysql': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'muhangiki_wallet', # Remplacez par le nom de votre base de données
        'USER': 'root', # Remplacez par votre utilisateur de base de données
        'PASSWORD': '', # Remplacez par votre mot de passe de base de données
        'HOST': 'localhost',
        'PORT': '3306',
    },
    'postgres': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'muhangiki_wallet', # Remplacez par le nom de votre base de données
        'USER': 'postgres', # Remplacez par votre utilisateur de base de données
        'PASSWORD': '', # Remplacez par votre mot de passe de base de données
        'HOST': 'localhost',
        'PORT': '5432',
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr-FR'

TIME_ZONE = 'Africa/Lubumbashi'

USE_I18N = True

USE_TZ = True

# Page de connection
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'login'

# Configuration de l'authentification
AUTH_USER_MODEL = 'administrateurs.Users'

# Configuration de l'email
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'staticfiles' / 'media'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

STATICFILES_DIRS = [
    MEDIA_ROOT
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration de crispy_forms
CRISPY_TEMPLATE_PACK = 'bootstrap4' # Configuration de crispy_forms

# Configuration de bootstrap5
BOOTSTRAP5 = {
    'include_jquery': True,
    'use_bootstrap_5': True,
}




#confugurations relative a celery

CELERY_BROKER_URL = 'redis://localhost:6379/0'
# Optionnel : Backend pour stocker les résultats des tâches
# CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Lubumbashi'  # Ajustez votre timezone (pour Goma, pourrait être 'Africa/Lubumbashi' ou 'Africa/Kinshasa')

CELERY_BEAT_SCHEDULE = {
    'hello-world-every-2-seconds': {
        'task': 'membres.tasks.hello_world_task',
        'schedule': 2.0,
    },
}